
Version: 0.17.79
#ScriptWorkspaceDir: '/home/factorio/data'
ScriptWorkspaceDir: 'D:\FactorioSUT_Temp\data'
SaveName: 'factorio'
Credentials:
  User: 'arch1en'
  Token: 'f11dac7975c63b644d3f178f62525a'
Mods:
  - Name: 'bobvehicleequipment'