Common:
    ApplicationName: Valheim
    ApplicationSteamID: 896660
    ScriptWorkspaceDir: '/home/valheim/script_workspace'

ServerData:
    Maniga:
        ServerDataDir: /home/valheim/servers/maniga